name: Deploy Student Portal

on:
  push:
    branches: [main]
    paths:
      - "frontend/apps/student-portal/**"
      - "frontend/libs/**"
      - "frontend/package.json"
  workflow_dispatch:

jobs:
  deploy-student-portal:
    name: Build and Deploy Student Portal to Azure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@4.4.0
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Run tests for Student Portal
        run: npm run test student-portal -- --watch=false --browsers=ChromeHeadless
        working-directory: frontend

      - name: Build Student Portal
        run: npm run build student-portal -- --configuration production
        working-directory: frontend

      - name: Archive Student Portal build
        uses: actions/upload-artifact@v4.6.2
        with:
          name: student-portal-build
          path: frontend/dist/apps/student-portal

      - name: Download artifacts
        uses: actions/download-artifact@v4.2.1
        with:
          name: student-portal-build
          path: frontend/dist/apps/student-portal

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Student Portal to Azure Static Web App
        id: deploy-student-portal
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_STUDENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/dist/apps/student-portal"
          api_location: ""
          output_location: ""
