# name: Deploy Student Portal

# on:
#   workflow_run:
#     workflows: ["Unit Tests"]
#     branches: [main]
#     types:
#       - completed
#   workflow_dispatch:

# jobs:
#   deploy-student-portal:
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     name: Build and Deploy Student Portal to Azure
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4.2.2

#       - name: Setup Node.js
#         uses: actions/setup-node@v4.4.0
#         with:
#           node-version: "20.x"
#           cache: "npm"
#           cache-dependency-path: frontend/package-lock.json

#       - name: Install dependencies
#         run: npm ci
#         working-directory: frontend

#       - name: Build Student Portal
#         run: npm run build:student
#         working-directory: frontend

#       - name: Debug build output
#         run: |
#           echo "Build output directory structure:"
#           find frontend/dist -type f | sort

#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Deploy Student Portal to Azure Static Web App
#         id: deploy-student-portal
#         uses: Azure/static-web-apps-deploy@v1
#         with:
#           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_STUDENT_TOKEN }}
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           action: "upload"
#           app_location: "frontend/dist/student-portal/browser"
#           api_location: ""
#           output_location: ""
#           skip_app_build: true
