name: Develop CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  build-backend:
    name: Build .NET Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore backend/Vanguard.sln

      - name: Build
        run: dotnet build backend/Vanguard.sln --configuration Release --no-restore

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: backend-build
          path: backend/src/**/bin/Release/

  build-student-portal:
    name: Build Student Portal
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build Student Portal
        run: npm run build student-portal
        working-directory: frontend

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: student-portal-build
          path: frontend/dist/apps/student-portal/

  build-teacher-portal:
    name: Build Teacher Portal
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build Teacher Portal
        run: npm run build teacher-portal
        working-directory: frontend

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: teacher-portal-build
          path: frontend/dist/apps/teacher-portal/
